spring.application.name=ApiGateway

server.port=9000

#Hablilitar el regsitro de centralizado de los ms
spring.cloud.gateway.discovery.locator.enabled=true

#Registro de los MS

#1 La url del servidor local del ms
spring.cloud.gateway.routes[0].id=MS-ESCUELAS
spring.cloud.gateway.routes[0].uri=http://localhost:8764
# Predicates[0] nos obtiene las sentencias de codigo sql de la bd, siempre va en 0
spring.cloud.gateway.routes[0].predicates[0]=Path=/escuelas/**


#Estudiantes
spring.cloud.gateway.routes[1].id=MS-ESTUDIANTES
spring.cloud.gateway.routes[1].uri=http://localhost:8763
spring.cloud.gateway.routes[1].predicates[0]=Path=/estudiantes/**


#Cursos
spring.cloud.gateway.routes[2].id=MS-COURSES
spring.cloud.gateway.routes[2].uri=http://localhost:8762
spring.cloud.gateway.routes[2].predicates[0]=Path=/cursos/**


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
# Mantiene solo una cabecera de CORS si los MS intentan enviar otra
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST