-- BASE DE DATOS DE MICROSERVICIOS

-- MS SCHOOL -- ORACLE

CREATE TABLE ESCUELAS(
ID_ESCUELA NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(90) NOT NULL,
CLAVE VARCHAR(90) NOT NULL,
FECHA_APERTURA DATE
);


--- MS COURSES -- H2 (BASE DE DATOS EN MEMORIA)


-- MS STUDENTS -- ORACLE
CREATE TABLE ESTUDIANTES(
ID_ESTUDIANTE NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(90) NOT NULL,
APP VARCHAR2(90) NOT NULL,
APM VARCHAR2(90) NOT NULL,
ID_ESCUELA NUMBER NOT NULL
);

INSERT INTO ESCUELAS VALUES(1,'CENTRO ESCOLAR MELQUIADES','65654DFDF','12/02/2000');

INSERT INTO ESTUDIANTES VALUES(1,'ISMAEL','MARTINEZ','URUETA',1);
COMMIT;
SELECT * FROM ESTUDIANTES;


