ALTER SESSION SET CURRENT_SCHEMA = escuela;

CREATE TABLE ESCUELAS(
ID_ESCUELA NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(90) NOT NULL,
CLAVE VARCHAR(90) NOT NULL,
FECHA_APERTURA DATE
);

CREATE TABLE ESTUDIANTES(
ID_ESTUDIANTE NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(90) NOT NULL,
APP VARCHAR2(90) NOT NULL,
APM VARCHAR2(90) NOT NULL,
ID_ESCUELA NUMBER NOT NULL
);

INSERT INTO ESCUELAS VALUES(1,'CENTRO ESCOLAR MELQUIADES','65654DFDF', TO_DATE('12/02/2000','DD/MM/YYYY'));
INSERT INTO ESTUDIANTES VALUES(1,'ISMAEL','MARTINEZ','URUETA',1);
COMMIT;
