spring.application.name=MS-COURSES


#Puerto del servidor
server.port=8762

# Configuracion de la fecha
spring.jackson.time-zone=America/Mexico_City

#Configuracion Eureka server
eureka.instance.hostname=localhost
eureka.client.service-url.defaulZone=http://localhost:8761/eureka
# Desactivar reintentos automáticos de Feign
